// Auto generated by TagsAndLayersGenerator.cs
// Created at 2024/10/30 下午 02:53:49



public static class Layers {
	public const string Default = "Default";
	public const string TransparentFX = "TransparentFX";
	public const string IgnoreRaycast = "Ignore Raycast";
	public const string Water = "Water";
	public const string UI = "UI";
}
