// Auto generated by TagsAndLayersGenerator.cs
// Created at 2024/11/19 下午 10:18:54



namespace zer0
{
    public static class Layers
    {
        public const string Default = "Default";
        public const string TransparentFX = "TransparentFX";
        public const string IgnoreRaycast = "Ignore Raycast";
        public const string Water = "Water";
        public const string UI = "UI";
    }
}
