// Auto generated by TagsAndLayersGenerator.cs
// Created at 2024/11/19 下午 10:18:53



namespace zer0
{
    public static class Tags
    {
        public const string Untagged = "Untagged";
        public const string Respawn = "Respawn";
        public const string Finish = "Finish";
        public const string EditorOnly = "EditorOnly";
        public const string MainCamera = "MainCamera";
        public const string Player = "Player";
        public const string GameController = "GameController";
    }
}
